import { SuppliersListPage }          from "./suppliers/SuppliersListPage";
import { SupplierCardPage }           from "./suppliers/SupplierCardPage";
import { PurchasesListPage }          from "./invoices/PurchasesListPage";
import { PurchaseInvoiceEditorPage }  from "./invoices/PurchaseInvoiceEditorPage";
import { PurchaseInvoiceViewPage }    from "./invoices/PurchaseInvoiceViewPage";
import { PurchaseOrdersListPage }     from "./orders/PurchaseOrdersListPage";
import { PurchaseReturnsPage }        from "./returns/PurchaseReturnsPage";
import { PurchaseVouchersPage }       from "./vouchers/PurchaseVouchersPage";
import { InboundEtaPage }             from "./inbound-eta/InboundEtaPage";

export { SuppliersListPage         as SuppliersPage           };
export { SupplierCardPage          as SupplierCard             };
export { PurchasesListPage         as PurchasesPage            };
export { PurchaseInvoiceEditorPage as PurchaseInvoiceEditor    };
export { PurchaseInvoiceViewPage   as PurchaseInvoiceView      };
export { PurchaseOrdersListPage    as OrdersPage               };
export { PurchaseReturnsPage       as ReturnsPage              };
export { PurchaseVouchersPage      as VouchersPage             };
export { InboundEtaPage            as InboundEtaHubPage        };
