import { FinanceDashboardPage as _Dashboard }   from "./dashboard/FinanceDashboardPage";
import { TreasuriesPage as _Treasuries }        from "./treasuries/TreasuriesPage";
import { ExpensesPage as _Expenses }            from "./expenses/ExpensesPage";
import { ReceiptVouchersPage as _Receipts }     from "./receipts/ReceiptVouchersPage";
import { PaymentVouchersPage as _Payments }     from "./payments/PaymentVouchersPage";
import { TransfersPage as _Transfers }          from "./transfers/TransfersPage";
import { JournalPage as _Journal }              from "./journal/JournalPage";
import { CoaPage as _Coa }                     from "./coa/CoaPage";
import { TrialBalancePage as _TrialBalance }    from "./trial-balance/TrialBalancePage";
import { StatementsPage as _Statements }        from "./statements/StatementsPage";
import { ReconciliationPage as _Reconciliation } from "./reconciliation/ReconciliationPage";
import { ClosingPage as _Closing }              from "./closing/ClosingPage";

export const FinanceDashboardPage  = _Dashboard;
export const TreasuriesPage        = _Treasuries;
export const ExpensesPage          = _Expenses;
export const ReceiptVouchersPage   = _Receipts;
export const PaymentVouchersPage   = _Payments;
export const FinanceTransfersPage  = _Transfers;
export const JournalPage           = _Journal;
export const CoaPage               = _Coa;
export const TrialBalancePage      = _TrialBalance;
export const StatementsPage        = _Statements;
export const ReconciliationPage    = _Reconciliation;
export const ClosingPage           = _Closing;
