import { create } from "zustand";
import { getChecks } from "@/lib/mock/play";
import type { Check } from "@/features/play/types";

const SEED_CHECKS: Record<string, Check> = Object.fromEntries(
  getChecks().map((c) => [c.id, c])
);

let seq = 1;
export function nextCheckId(): string {
  return `chk_${Date.now()}_${seq++}`;
}

interface PlayChecksState {
  checks: Record<string, Check>;
  /** A brand-new session always owns a brand-new, empty check (cafeteria lines land on it in
   * a later step — this step only needs the check to exist so `check_id` resolves). `id` is
   * generated by the caller (via `nextCheckId`) up front, since `Session.check_id` must be set
   * at the same moment the session itself is created — the two records reference each other. */
  createCheck: (id: string, sessionId: string) => Check;
}

export const usePlayChecks = create<PlayChecksState>()((set) => ({
  checks: SEED_CHECKS,

  createCheck: (id, sessionId) => {
    const check: Check = { id, session_id: sessionId, cafeteria_lines: [] };
    set((s) => ({ checks: { ...s.checks, [check.id]: check } }));
    return check;
  },
}));
