import { create } from "zustand";
import { persist } from "zustand/middleware";
import { getChecks } from "@/lib/mock/play";
import type { CafeteriaLine, Check, Product } from "@/features/play/types";

const SEED_CHECKS: Record<string, Check> = Object.fromEntries(
  getChecks().map((c) => [c.id, c])
);

let seq = 1;
export function nextCheckId(): string {
  return `chk_${Date.now()}_${seq++}`;
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

interface PlayChecksState {
  checks: Record<string, Check>;
  /** A brand-new session always owns a brand-new, empty check (cafeteria lines land on it in
   * a later step — this step only needs the check to exist so `check_id` resolves). `id` is
   * generated by the caller (via `nextCheckId`) up front, since `Session.check_id` must be set
   * at the same moment the session itself is created — the two records reference each other. */
  createCheck: (id: string, sessionId: string) => Check;
  /** §5.4 — adds one unit of `product` to the check's cafeteria lines, or increments qty if
   * that product is already on the check (tap-to-add, mirroring F&B/POS grid taps). Never
   * blocks on `product.has_bom` (flag-don't-block) — it only stamps `has_bom` onto the line. */
  addCafeteriaLine: (checkId: string, product: Product) => void;
}

export const usePlayChecks = create<PlayChecksState>()(
  persist(
    (set) => ({
      checks: SEED_CHECKS,

      createCheck: (id, sessionId) => {
        const check: Check = { id, session_id: sessionId, cafeteria_lines: [] };
        set((s) => ({ checks: { ...s.checks, [check.id]: check } }));
        return check;
      },

      addCafeteriaLine: (checkId, product) => set((s) => {
        const check = s.checks[checkId];
        if (!check) return s;

        const existingIndex = check.cafeteria_lines.findIndex((l) => l.product_id === product.id);
        let cafeteria_lines: CafeteriaLine[];
        if (existingIndex >= 0) {
          const existing = check.cafeteria_lines[existingIndex];
          const qty = existing.qty + 1;
          const updated: CafeteriaLine = { ...existing, qty, line_total: round2(qty * existing.unit_price) };
          cafeteria_lines = check.cafeteria_lines.map((l, i) => (i === existingIndex ? updated : l));
        } else {
          const line: CafeteriaLine = {
            product_id: product.id,
            name_ar: product.name_ar,
            qty: 1,
            unit_price: product.price,
            line_total: product.price,
            ...(product.has_bom && { has_bom: true }),
          };
          cafeteria_lines = [...check.cafeteria_lines, line];
        }
        return { checks: { ...s.checks, [checkId]: { ...check, cafeteria_lines } } };
      }),
    }),
    { name: "flexova.play.checks" }
  )
);
